### ISSUE TITLE
Deb package?

### ISSUE THREAD

**Issue by orschiro** [krrr/Hazama#1]
Dear @krrr,

What a great application!

Do you have a deb package to install on Ubuntu 16.10? :-)

**Comment by krrr** [comment]
No deb because I'm lazy😓. I will make one

**Comment by orschiro** [comment]
Cool, thank you! :-)

**Comment by krrr** [comment]
Here is the deb: https://github.com/krrr/Hazama/releases/download/v1.0.1/hazama_1.0.1_all.deb
Install and then run `sudo apt-get -f install` should work

**Comment by orschiro** [comment]
Your package is working perfectly. Thank you! :-)
