### ISSUE TITLE
Flatpak or AppImage

### ISSUE THREAD

**Issue by baimafeima** [krrr/Hazama#3]
Could you make a more universal package release such as Flatpak or AppImage? I don't use a Debian or Ubuntu-based operating system.

**Comment by krrr** [comment]
i want to replace deb with appimage, but it's harder than i imagined...
maybe you have to wait for a few weeks

**Comment by krrr** [comment]
what is your distro and its version?

**Comment by baimafeima** [comment]
I use Solus, a rolling release operating system: https://solus-project.com/

**Comment by krrr** [comment]
I made one: https://mega.nz/#!DRJFkDQA!cbEmhH1Kwx8yJsuHlzo_VkzQJIUn3MlNCdjD_FkB_18

please help me testing

**Comment by baimafeima** [comment]
I cannot access your link from China. Can you add this release here on GitHub?

**Comment by krrr** [comment]
直接说中文好了。不知道你是哪个运营商，我是可以直接上的
https://pan.baidu.com/s/1o7PFkWa
