### ISSUE TITLE
SyntaxError

### ISSUE THREAD

**Issue by luckypoem** [krrr/Hazama#6]
hi.

yudeMacBook-Air:Hazama brite$ ls
LICENSE		debian		hazama.py	setup.py	utils
README.md	hazama		res		translation
yudeMacBook-Air:Hazama brite$ python setup.py build_qt
  File "setup.py", line 30
SyntaxError: Non-ASCII character '\xe6' in file setup.py on line 31, but no encoding declared; see http://python.org/dev/peps/pep-0263/ for details
yudeMacBook-Air:Hazama brite$ 

怎么解决？

**Comment by krrr** [comment]
这种问题你应该问百度
