### ISSUE TITLE
Data sync betwenn linux and windows versions

### ISSUE THREAD

**Issue by Chrisch76** [krrr/Hazama#7]
Hello
I love your diary, thanks very much.
Which folder/file have i to sync over a cloud, to see the same entries of hazama on the laptop with  linux an the windows pc?
Thanks for answering.

sincerly, Chris

**Comment by krrr** [comment]
default data location:
Windows=%APPDATA%\Hazama
Linux=$HOME/.config/Hazama

**Comment by Chrisch76** [comment]
Hey krrr
Thank you very much...
have a nice day...
Greetings from Switzerland, Chris

**Comment by Chrisch76** [comment]
Perfect, it works! Thanks a lot
